// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Qa34Mlbab6fswJOYOP7-6cxGrM6Dk-k',
    appId: '1:932624635949:web:34f33e93087e2b641ac0a4',
    messagingSenderId: '932624635949',
    projectId: 'kyodai-sns',
    authDomain: 'kyodai-sns.firebaseapp.com',
    databaseURL: 'https://kyodai-sns-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kyodai-sns.firebasestorage.app',
    measurementId: 'G-8NHT33RJ6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM3zgxEtS1gOndNuId2kWiSj9gKjxVrUc',
    appId: '1:932624635949:android:cd43745f8e5a9a1c1ac0a4',
    messagingSenderId: '932624635949',
    projectId: 'kyodai-sns',
    databaseURL: 'https://kyodai-sns-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kyodai-sns.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2EYJjj-ogkACjgyInD_9JA6oj8ps51Ls',
    appId: '1:932624635949:ios:1dde612567476a5e1ac0a4',
    messagingSenderId: '932624635949',
    projectId: 'kyodai-sns',
    databaseURL: 'https://kyodai-sns-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kyodai-sns.firebasestorage.app',
    iosBundleId: 'com.example.kyotoExamHub',
  );
}
